const varDefault = {
  TipoCliente: '1',
  SegundoNombre: '',
  Nacionalidad: 'BOLIVIA',
  NivelEdu: '',
  TipoDoc: '1',
  NroRuc: '',
  FechaVencRuc: '',
  CodCiiu: '74990',
  Categoria: '',
  TelfOfi: '',
  TelfCasilla: '',
  Tipo: '',
  Ciudad: '',
  Correspondencia: '',
  NroCasilla: '',
  NroNit: '',
  VencNit: '',
  FechaConstitucion: '',
  CodRubro: '',
  CodSector: '',
  Actividad: '',
  AdicionalNac: '',
  NacDesc: '',
  FormaLlegada: '',
  RepLegal: '',
  RepLegalDesc: ''
}

export default varDefault
